### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Jetaime-Alexandria**
Hello, I am making this pull-request because I've been suff.

### CODE REVIEW

**Comment by Jetaime-Alexandria** [comment]
Well you see, I don't really know what you mean by that, but it's a pull request filled with changes because you disabled the option for me to push to dev and/or master and force me to do it this way.

**Review by JacubRSTNC — CHANGES_REQUESTED** [review]
Update version.json to reflect new changes.

**Review by JacubRSTNC — APPROVED** [review]
LGTM

**Review by JacubRSTNC — CHANGES_REQUESTED** [review]
Ehh be more professional actually

**Review by JacubRSTNC — APPROVED** [review]
Actually seems good this time around

**Pull request merged**
